### Obtener todas las categorias
GET http://localhost:3001/api/categories

### Obtener categoria por ID
GET http://localhost:3001/api/categories/66d13935354529e3fd86c7e6

### Crear categoria
POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "name": "Juguetes"
}

### Actualizar categoria
PATCH  http://localhost:3001/api/categories/66d13a187ca0516d12633343
Content-Type: application/json

{
    "name": "Jardineria"
}

### Eliminar categoria
DELETE   http://localhost:3001/api/categories/66d13a187ca0516d12633343