### Obtener todas las categorias
GET http://localhost:3001/api/categories

### Obtener categoria por ID
GET http://localhost:3001/api/categories/66d1395d354529e3fd86c7f1

### Crear categoria
POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "name": "Juguetes"
}

### Actualizar categoria
PATCH  http://localhost:3001/api/categories/66d1395d354529e3fd86c7f1
Content-Type: application/json

{
    "name": "Libros"
}

### Eliminar categoria
DELETE   http://localhost:3001/api/categories/66d13a187ca0516d12633343