### Obtener todos los productos
GET http://localhost:3001/api/products

### Obtener producto por id
GET http://localhost:3001/api/products/66cff11151335806e20c58ed

### Crear producto
POST http://localhost:3001/api/products/
Content-Type: application/json

{
    "name": "Laptop",
    "description": "Laptop marca HP con resolcion 1080p almacenamiento 500gb SSD 16 ram DDR4 procesador core I5 12th",
    "quantity": 0,
    "price": 500,
    "category_id": "66d13935354529e3fd86c7e6",
    "supplier_id": "66d1442872070e89687aca78"
}

### Editar producto
PUT http://localhost:3001/api/products/66d1476113a2f2d99fa48526
Content-Type: application/json

{
    "supplier_id": "66d1445372070e89687aca7a",
    "category_id": "66d13943354529e3fd86c7ea"
}

### Eliminar producto
DELETE  http://localhost:3001/api/products/66d372524c29ad48d4e010fc